version: '3.9'

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./.srv/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: Yheo372Yd
      MYSQL_DATABASE: wooeshop
      MYSQL_USER: merantauw
      MYSQL_PASSWORD: 56Ndq973

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: merantauw
      WORDPRESS_DB_PASSWORD: 56Ndq973
      WORDPRESS_DB_NAME: wooeshop
      WORDPRESS_DEBUG: 1
    volumes:
      - ./.srv/wordpress/:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/mera
      - ./plugin:/var/www/html/wp-content/plugins/mera-core
      - ./.srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: merantauw
      MYSQL_ROOT_PASSWORD: Yheo372Yd
      PMA_HOST: mysql